version: '3.4'

services:
  notifications:
    image: notifications-api
    restart: on-failure
    ports:
      - 8081:8081
    network_mode: host
  preferences:
    image: notifications-preferences
    restart: on-failure
    ports:
      - 8082:8082
    network_mode: host
  template:
    image: notifications-template
    restart: on-failure
    ports:
      - 8083:8083
    network_mode: host
  channel-email:
    image: notifications-channel-email
    restart: on-failure
    ports:
      - 8084:8084
    network_mode: host
  channel-mobile-push:
    image: notifications-channel-mobile-push
    restart: on-failure
    ports:
      - 8085:8085
    network_mode: host
  channel-sms:
    image: notifications-channel-sms
    restart: on-failure
    ports:
      - 8086:8086
    network_mode: host
  channel-web-push:
    image: notifications-channel-web-push
    restart: on-failure
    ports:
      - 8087:8087
    network_mode: host
  channel-whatsapp:
    image: notifications-channel-whatsapp
    restart: on-failure
    ports:
      - 8088:8088
    network_mode: host
  #audit:
  #   image: notifications-audit
  #  restart: on-failure
  #  ports:
  #    - 8089:8089
  #  network_mode: host



